## Practice Questions for Pandas

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

```
4. Create a 4x4 NumPy array filled with random integers between 1 and 100. Then, reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, and return the results as two separate NumPy arrays


In [3]:
import pandas as pd

# Load the dataset
df = pd.read_csv('Cars93_miss.csv')

filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

filtered_df


Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [4]:
import pandas as pd

df = pd.read_csv('Cars93_miss.csv')

mean_min_price = df['Min.Price'].mean()
mean_max_price = df['Max.Price'].mean()

df['Min.Price'].fillna(mean_min_price, inplace=True)
df['Max.Price'].fillna(mean_max_price, inplace=True)

print(df.head())


  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0     

In [5]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

filtered_df = df[df.sum(axis=1) > 100]

print(filtered_df)


     0   1   2   3
1   35  35  31  30
2   25  32  37  11
4   16  33  36  19
8   26  15  38  31
9   27  28  32  30
10  33  18  26  30
11  35  23  39  33
13  20  21  32  34


In [6]:
import numpy as np

original_array = np.random.randint(1, 100, size=(4, 4))

rows_array = original_array.copy()
columns_array = original_array.T

sum_rows = lambda array: np.sum(array, axis=1)
sum_columns = lambda array: np.sum(array, axis=0)

rows_sum = sum_rows(rows_array)
columns_sum = sum_columns(columns_array)

original_array, rows_sum, columns_sum


(array([[71, 20, 60, 69],
        [ 6, 80, 85, 30],
        [81, 78, 32, 17],
        [21, 42, 17, 29]]),
 array([220, 201, 208, 109]),
 array([220, 201, 208, 109]))